"""empty message

Revision ID: 2417ffd5003b
Revises: 413039fd475e
Create Date: 2014-09-28 14:03:08.027720

"""

# revision identifiers, used by Alembic.
revision = '2417ffd5003b'
down_revision = '413039fd475e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('share_code', sa.Text(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery', 'share_code')
    ### end Alembic commands ###
