"""empty message

Revision ID: efceab33fad9
Revises: 4093ccb6d914
Create Date: 2016-03-26 15:23:01.262652

"""

# revision identifiers, used by Alembic.
revision = 'efceab33fad9'
down_revision = '4093ccb6d914'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], [u'gallery.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(
        table_name='gallery',
        column_name='share_code',
        nullable=False,
        type_=sa.String(255)
    )
    op.create_unique_constraint(None, 'gallery', ['share_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gallery', type_='unique')
    op.drop_table('photo')
    ### end Alembic commands ###
